source "https://rubygems.org"

ruby ">= 3.2"

gem "rails", "7.1.3"
gem "pg"
gem "puma", ">= 6.0"

group :development do
  gem "pry-rails"
  gem "rubocop", require: false
end

group :test do
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails"
end
